# Generated by Django 6.0.3 on 2026-03-23 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('short_description', models.CharField(max_length=255, verbose_name='descripción breve')),
                ('icon', models.CharField(choices=[('advice', 'Asesoría'), ('valuation', 'Valuación'), ('credit', 'Créditos'), ('marketing', 'Marketing')], default='advice', max_length=20, verbose_name='icono')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='foto')),
                ('quote', models.TextField(verbose_name='testimonio')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='calificación')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('is_published', models.BooleanField(default=True, verbose_name='publicado')),
            ],
            options={
                'verbose_name': 'testimonio',
                'verbose_name_plural': 'testimonios',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
