# Generated by Django 6.0.3 on 2026-03-23 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('icon_style', models.CharField(choices=[('building', 'Edificio'), ('monument', 'Monumento'), ('pin', 'Pin de mapa')], default='pin', max_length=20, verbose_name='estilo de icono')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'colonia',
                'verbose_name_plural': 'colonias',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('listing_type', models.CharField(choices=[('buy', 'Compra'), ('rent', 'Renta')], default='buy', max_length=10, verbose_name='tipo de operación')),
                ('property_type', models.CharField(choices=[('house', 'Casa'), ('apartment', 'Departamento'), ('land', 'Terreno'), ('office', 'Oficina')], default='house', max_length=20, verbose_name='tipo de propiedad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='precio')),
                ('currency', models.CharField(default='MXN', max_length=3, verbose_name='moneda')),
                ('borough', models.CharField(blank=True, max_length=120, verbose_name='alcaldía')),
                ('address_line', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('square_meters', models.PositiveIntegerField(blank=True, null=True, verbose_name='m²')),
                ('parking_spots', models.PositiveSmallIntegerField(default=0, verbose_name='estacionamientos')),
                ('featured', models.BooleanField(default=False, verbose_name='destacada')),
                ('published', models.BooleanField(default=True, verbose_name='publicada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.neighborhood', verbose_name='colonia')),
            ],
            options={
                'verbose_name': 'propiedad',
                'verbose_name_plural': 'propiedades',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/%Y/%m/', verbose_name='imagen')),
                ('is_primary', models.BooleanField(default=False, verbose_name='principal')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='propiedad')),
            ],
            options={
                'verbose_name': 'imagen de propiedad',
                'verbose_name_plural': 'imágenes de propiedades',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['featured', 'listing_type'], name='properties__feature_659586_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties__price_32e7c2_idx'),
        ),
    ]
